### ISSUE TITLE
Publish core conversion code as npm package

### ISSUE THREAD

**Issue by alloy** [DanielsWrath/YNABGoingDutch#41]
**Is your feature request related to a problem? Please describe.**

As a developer, I want to be able to fully automate my import pipeline, so that I don’t need to manually drag and drop too much.

**Describe the solution you'd like**

If the core conversion code were published as a standalone package, I would be able to easily use it directly in a custom workflow.

For instance, on my macOS machine I can attach a script to the `Downloads` folder that automatically invokes the conversion for csv files that match the expected filenames and do some further processing such as giving the files account names that correspond to the names I use in YNAB.

**Additional context**

Thanks for your work and releasing this! 🙏

**Comment by alloy** [comment]
(FYI I’m willing to do as much of the work as you feel comfortable with.)

**Comment by alloy** [comment]
I realise that adding package publication requires some overhead and I actually wouldn’t need that for my purposes, in fact the only thing needed would likely be a `package.json` file so I can point yarn/npm at the GitHub repo directly.

**Comment by DanielsWrath** [comment]
Hmm, I have never created a publishable npm package. Would be interested in some other people's ideas, so I will ask around a little for the best practices. I understand your problem and would definitely be willing to create one, but I think it would be cleaner to create a separate repo containing the npm image. The only problem would be that this repo should be updated separately, because YNABGoingDutch uses plain JS which cannot use npm, as far as I know.

**Comment by alloy** [comment]
Yeah perhaps cleaner indeed, I just don’t want to cause you any maintainer burden for something that perhaps only I end up using. If you’d prefer, let me know and I’ll whip up a PR that would show how to do the least work to make this repo consumable.
